chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("room/<int:course_id>", views.course_chat_room, name='course_chat_room'),
]

e_learning_platfrom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from courses.views import CourseListView

urlpatterns = [
    # --- auth routes(done)
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    # ---admin panel(done)
    path('admin/', admin.site.urls),
    # ---Course Views (Done)
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    # ---Student Views (Done)
    path('students/', include('students.urls')),
    # ---API >> Courses (Done)
    path('api/', include('courses.api.urls', namespace='api/')),
    # ---the chat rooms for the courses
    path('chat/', include('chat.urls', namespace='chat/')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views

urlpatterns = [
    # ...creating a new student account
    path('register/', views.StudentRegistrationView.as_view(), name='student_registration'),
    # ...add the student to the course list of students
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    # ...list of all the courses the user is enrolled in
    path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
    # ...course detail page + course chat room
    path('coursjes/<pk>/', views.StudentCourseDetailView.as_view(), name='student_course_detail'),
    # ...showing the contents of a course module
    path('courses/<pk>/<module_id>', views.StudentCourseDetailView.as_view(), name='student_course_detail_module'),
    # ...using caching to cache a view
    # path('courses/<pk>/', cache_page(60 * 15)(views.StudentCourseDetailView.as_view()), name='student_course_detail'),
    # path('courses/<pk>/<module_id>', cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
    #      name='student_course_detail_module'),

]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all(), widget=forms.HiddenInput)

students/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CourseEnrollForm
from courses.models import Course


class StudentRegistrationView(CreateView):
    template_name = "students/student/registration.html"
    form_class = UserCreationForm
    success_url = reverse_lazy('student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)

        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)

        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('student_course_detail', args=[self.course.id])


# ---------Student Course view
class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/student/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(DetailView):
    model = Course
    template_name = 'students/student/detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        course = self.get_object()

        if 'module_id' in self.kwargs:
            context['module'] = course.modules.get(id=self.kwargs['module_id'])
        else:
            if course.modules.all():
                context['module'] = course.modules.all()[0]

        return context

students/templates/students/student/detail.html
{% extends 'base.html' %}
{#{% load cache %}#}
{% load static %}
{% block title %}{{ object.title }}{% endblock %}

{% block page_title %}
    {{ module.title }}
{% endblock %}

{% block content %}
    {# the side-bar #}
    <div class="contents">
        <h3 class="display-6">Modules</h3>
        <ul>
            {% for m in object.modules.all %}
                <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
                    <a href="{% url 'student_course_detail_module' object.id m.id %}">
                        <span>
                            Module <span class="order">{{ m.order|add:1 }}</span>
                        </span>
                        <br>
                        {{ m.title }}
                    </a>
                </li>
            {% empty %}
                <li>No Modules Yet.</li>
            {% endfor %}
        </ul>

        <div>
            <h3 class="display-6 hover-style">
                <a href="{% url 'chat:course_chat_room' object.id %}">
                    Chat Room ==>
                </a>
            </h3>

        </div>
    </div>

    <div class="module">
{#    {% cache 300 module_content_s module%}#}
        {% for content in module.contents.all %}
            {% with item=content.item %}
                <div class="module card" >
                    <details>
                        <summary>
                            <span class="display-6 p-1">{{ item.title }}</span>
                        </summary>

                        {{ item.render }}

                    </details>
                </div>

            {% endwith %}
        {% endfor %}
{#    {% endcache %}#}
    </div>
{% endblock %}

students/templates/students/student/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyCourses{% endblock %}

{% block page_title %}
    My courses
{% endblock %}

{% block content%}

    <div class="module shadow-style w-100">
        {% for course in object_list %}
            <div class="card p-1 text-center hover-style">
                <h3 class="display-6">{{ course.title }}</h3>
                <p>
                    <a class="btn btn-primary text-white" href="{% url 'student_course_detail' course.id %}">Access Contents</a>
                </p>
            </div>

        {% empty %}
            <p class="text-primary display-6">you are not enrolled in any courses yet</p>
            <a class="btn btn-success text-white" href="{% url 'course_list' %}">Browse Course</a> to enroll in a course
        {% endfor %}
    </div>
{% endblock %}

students/templates/students/student/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block page_title %}
    Sign Up
{% endblock %}

{% block content %}
    <div class="module shadow-style w-100">
        <h2 class="card p-4 text-center text-white bg-primary">Enter you details to create a student account</h2>
        <form class="form" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input class="bg-primary" type="submit" value="Create the account"></p>
        </form>
    </div>
{% endblock %}